### ISSUE TITLE
choose sampleset names for expression datasets

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/datastore#11]
HI Sudhansu-
can you take a look ASAP and choose sample set names for the expression folders that Sam put in the
datastore following our conversation from several weeks ago:
ICPL87119.gnm1.ann1.samplesetN.expr1.4H6Z
ICC4958.gnm2.ann1.samplesetN.expr1.4Y7B
Wm82.gnm2.ann1.samplesetN.expr1.G7ZY
G19833.gnm1.ann1.samplesetN.expr1.4ZDQ
IT97K-499-35.gnm1.ann1.samplesetN.expr1.BWH5

I can dig up the google doc/email we worked on together for that RFO if needed but as I recall these
are simply meant to be short(ish) and meaningful (human-readable) representations of the
set of samples that will be reused whenever the same dataset gets reused. Perhaps something like
Libault2010Atlas for the soybean one? I don't have any strong feelings about it, but samplesetN
clearly needs to be changed (if only because they are different samplesets!). If you'd prefer I chose
names just let me know.

**Comment by cann0010** [comment]
If I may weigh in ... the directory names are brief, not descriptive. Versioning doesn't really apply to expression sets (version is relevant for an assembly or annotation, but expression sets are independent of one another). I suggest this form:
ICPL87119.gnm1.ann1.expr.4H6Z
ICC4958.gnm2.ann1.expr.4Y7B
Wm82.gnm2.ann1.expr.G7ZY
G19833.gnm1.ann1.expr.4ZDQ
IT97K-499-35.gnm1.ann1.expr.BWH5
The descriptive information about the contents (e.g. Libault 2010 expression atlas) is presented in the "subject" field of the README ... which gets used to create the "Overview of data in this directory" that's displayed at the top of e.g. https://v1.legumefederation.org/data/public/Glycine_max/

**Comment by adf-ncgr** [comment]
@cann0010 this was RFO'd some time ago- I'll fwd the email that justifies the introduction of sampleset names and versions. This was the result of a discussion we had to harmonize the needs of what Sudhansu was doing with expression data with Sam's intermine requirements. 
If you still feel strongly about it let us know but I think it's well past the object-by date ;)

**Comment by cann0010** [comment]
Yes, if you could share that RFO please. I don't recall it.

**Comment by adf-ncgr** [comment]
I fwd'd it via email; sorry my response may have been a bit terse, we spent a long time on that discussion (and in retrospect perhaps we should have invited you but I wasn't anticipating it to become the conversation that it did). Please note in particular in that email the "implications for other dataset types" and the precedent referenced for https://legumeinfo.org/data/public/Arachis_hypogaea/minicore_Dezern.trt.JWYM/
with respect to meaningful sample set names in folders. And if you do want to elaborate the datastore naming and structure philosophy for future rigorous consistency, you'll find me a willing (if not eager) listener/disputant :)

**Comment by cann0010** [comment]
I think the email probably did come across to me as fait accompli (rather than a RFO), so I didn't absorb it as I should have. Whatever the reasons for my inattention, the implications of the design elements didn't sink in then. Reading that email closely now, I see the rationale for identifying versions of the sampleset and expression. 

Granting the new proposed directory-name fields, I am not enthusiastic about  a free-form sample description being used for the fourth element being (e.g. G19833.gnm1.ann1.ORourke_phavu_atlas1.expr1.4ZDQ). Parsing becomes harder. We've mostly tried to keep the directory names semantically simple and well-structured - and to leave the associated descriptive information in the Overview text. I prefer the form of Sam's shorter placeholder version ... which I would shorten as much as possible (long names become problematic in our browser implementation, because the right side gets truncated):
G19833.gnm1.ann1.set1.expr1.4ZDQ
ICPL87119.gnm1.ann1.set1.expr1.4H6Z

Regarding the ordering of the sampleset and expression fields: are samplesets used for anything apart from expression? If not, then it may make sense to swap the order, i.e. expr1.set1
G19833.gnm1.ann1.expr1.set1.4ZDQ
ICPL87119.gnm1.ann1.expr1.set1.4H6Z

**Comment by sdash-github** [comment]
>Regarding the ordering of the sampleset and expression fields: are 
samplesets used for anything apart from expression? If not, then it may 
make sense to swap the order, i.e. expr1.set1
G19833.gnm1.ann1.expr1.set1.4ZDQ
ICPL87119.gnm1.ann1.expr1.set1.4H6Z

Would something like below will do?
G19833.gnm1.ann1.expr1.*phavu1*.4ZDQ
ICPL87119.gnm1.ann1.expr1.*cajca1*.4H6Z
The phavu1 and cajca1 strings make a strong connection/traceability to 
the OnGenome LIS dataset we are using here.  Of course, the Overview 
text can have all the other details that Sam needs for his mines in a 
structured way that he specifies and he uses for loading to the mines.  
(The phavu1 and cajca1 dataset accessions have all kinds of metadata 
details a user may need)

**Comment by cann0010** [comment]
Early on in the Data Store, we dropped the genus-species identifiers (phavu, cajca) in the collection (directory) names because that information is present in the containing species set (Phaseolus_vulgaris/). The genus-species field is also included in the individual files: phavu.G19833.gnm1.ann1.pScz.gene_models_main.gff3
So, no, I don't like **phavu1**.4ZDQ used in that position. That field should indicate the data type (expression in this case).

**Comment by sdash-github** [comment]
> "That field should indicate the data type (expression in this case)."

The string 'phavu1' although appears to reflect genus-species identifiers, it actually identifies an expression dataset in this context.  The combined suffix 'expr1.phavu1' means in this context an expression-dataset-identified-by-a-string-called-phavu1, that is, it is an expression data type. So it should satisfy the data-type criterion for this position in the name. In addition it also contains reference to all other information about this dataset and its samples.

**Comment by cann0010** [comment]
I don't get it. If phavu1 "appears to reflect genus-species," why would a user instead think that it means a kind of sample-set?

**Comment by sdash-github** [comment]
Let us say we consider these kinds of alternative names:
a. G19833.gnm1.ann1.expr1.set1.4ZDQ
b. G19833.gnm1.ann1.expr1.SRP046307.4ZDQ
c. G19833.gnm1.ann1.expr1.phavu1.4ZDQ
d. G19833.gnm1.ann1.expr1.someAgreedString.4ZDQ

The positional part "expr1.set1" in a. suggests expression data type identified by set1.
The positional part "expr1.SRP046307" in b. suggests expression data type identified by SRP046307.
The positional part "expr1.phavu1" in c. suggests expression data type identified by phavu1.
The positional part "expr1.someAgreedString" in d. suggests expression data type identified by someAgreedString.

Because of the postion in the entire name and prefix 'expr1' the combined part 'expr1.phavu1'  suggests datatype expression like any other agreed upon string; but because it is derived from another sub-project of LIS it has 'genspp' appearance. If it were derived from NCBI or GEO, it would have a NCBI/GEO-specified appearance like the example "expr1.SRP046307" which suggests a sample-set.  

So, although 'phavu1' in isolation appears to reflect genus-species; but  by virtue of its position and prefix expr1 it ( combined form 'expr1.phavu1' ) suggests an expression data type referencing a sample-set as specified in data-set phavu1 (or /set1/SRP046307/someAgreedString). 
The dot separating expr1 and phavu1 is needed for parsing, sam's requirement.

**Comment by adf-ncgr** [comment]
Hi-
it's been a while since I've read the document/email but I'm pretty sure we had agreed that the
"phavu1" style names would not be used for sample sets. I vaguely recall we had reasons for choosing the order of elements in the name that we did, but I'll need to refresh my memory. I think we had debated the use of NCBI accessions and decided against it for some reason, but again I'll need to refresh my memory. 

**We need to decide on a better way of making decisions.**

I am not sure when I'll have time to do the refresh but will try to weigh in more adequately soon.

**Comment by adf-ncgr** [comment]
OK, I've briefly refreshed my memory based on the paper trail we left (my email + the google doc around which we structured our conversation). We don't seem to have taken particularly good notes as to rationale. All I could find was this hint that ongenome accessions were to go into the READMEs:
README.KEY4.yml <-- OnGenome identifiers

Frankly, I don't really care what samplesets are named. I may have been misled into "human readable" by the example of :
https://legumeinfo.org/data/public/Arachis_hypogaea/minicore_Dezern.trt.JWYM/
which seems to be one of those folders that appear from time to time mysteriously without discussion and then the datastore-ologists try to infer things about the cultures that produced them :)
reluctantly dragging @sammyjava in to see if he has any vested interest in how sampleset names are chosen. All I really care about is that we try to adopt a consistent attitude that applies not only to expr but also other datasets that involve analysis or other representation of groups of samples (e.g. "trt").

**Comment by cann0010** [comment]
The relevant section in the "guiding document" for Data Store layout and naming is [here](https://github.com/LegumeFederationDataStore/about_the_data_store/blob/master/about_the_Data_Store.md#directory-structure-and-naming).

Expression data isn't explicitly covered in that document. Once we get this sorted out and accepted, we'll need to update the document.

I will say that as one of the "framers" of that document, the form "expr1.phavu1" doesn't feel right to me. It breaks the pattern that the middle fields indicate "analysis_type". There is nothing in "phavu1" that suggests analysis type ... and I don't think it is obvious that the preceding field (expr1) should lend it that connotation.

**Comment by sdash-github** [comment]
My memory about the naming that is missing in our googledoc is that Sam should have the expr1 mentioned and he doesn't care about what is mentioned in place of set1 in the name 'G19833.gnm1.ann1.expr1.set1.4ZDQ ' as long as a dot separates them for his parsing.

So, I argue for phavu1 because it gives me a clear reference to which dataset the data is coming from when I make the names in DS.  I 'think' Andrew interpreted this to  make use of  a human readable string that reminds of a specific expression dataset.

I agree, whatever we should decide should be consistent and user-cum-curation friendly.

**Comment by adf-ncgr** [comment]
OK, I see from the document Steven referenced in this section: https://github.com/LegumeFederationDataStore/about_the_data_store/blob/master/about_the_Data_Store.md#naming-phenotype-directories-and-files
gives us 
Naming phenotype directories and files:
Directory: [study-name].trt.[key]
Files: [species-abbreviation].[study-name].trt.[key].[descriptors/observations].xsl[x]
Example:

      minicore_Dezern.trt.Z0Z0/

so it seems like we are basically arguing about "what is a study-name" but in the case of expression datasets.

**Comment by sammyjava** [comment]
All I care is that the file names themselves are consistently named so I know which one is the list of samples (whatever.exprSamples.tsv), the matrix of genes/TPM values (whatever.genesSamplesTpm.tsv) and the description of the source/experiment (whatever.BWH5.exprSource.tsv). I don't use the extra chunk in the directory name, that's a Sudhansu request, and I explicitly reference the directory, anyway, so it can be anything. All I care about is that n-1.n = {exprSamples.tsv, genesSamplesTpm.tsv, exprSource.tsv}.

**Comment by adf-ncgr** [comment]
so are we at a point where we all agree that the folder naming will be as:
CDCFrontier.gnm1.ann1.sampleset4.expr1.GHTR/
ICC4958.gnm1.ann1.sampleset4.expr1.EFGH/

where sampleset4 is to be replaced by "something else" (pretty much up to the individual curator's tastes) and if the same "something else" recurs it implies that the same dataset was reanalyzed? 
this was in fact the original proposal as far as I can tell, but if someone can put more guidance around "something else", feel free...

**Comment by sammyjava** [comment]
Yeah, that's where we were at when I created the folders with the "samplesetN" placeholders, containing the three InterMine loader-certified files. I used "samplesetN" because that's the nomenclature we used in the discussion. In my world, it's an "RNA-seq experiment" and "experiment" is what NCBI calls it. It has a BioProject, likely a GEO, and SRA accessions. But I care not what that string is, as long as it doesn't have a dot in it.

**Comment by cann0010** [comment]
After some side discussion with Sudhansu, I think I better understand the rationale for this form:
G19833.gnm1.ann1.expr1.**phavu1**.4ZDQ
ICPL87119.gnm1.ann1.expr1.**cajca1**.4H6Z
The gensp# refers to the expression IDs used in the expression resources here: https://legumeinfo.org/lis_expression/all
So there is a tie-in to the nomenclature pattern in ongenome and those expression tools.

As for the ordering of the two new sub-fields (expr1.phavu1 or phavu1.expr1), I have a mild preference for the former, which suggests to me that this is something about expression - whereas I'm not sure (as a user) what phavu1 refers to. 

So, I think the abbreviated RFO is: 
Directory names for expression data sets will have the form:
GENOGYPE.gnm#.ann#.expr#.gensp#.KEY
... where {expr#.gensp#} together refers to an expression dataset, from a particular experiment.

Do I have that right?

**Comment by adf-ncgr** [comment]
following up without the benefit of further side discussion, I think the example (taken from our discussion document):
CDCFrontier.gnm1.ann1.sampleset4.expr1.GHTR/
ICC4958.gnm1.ann1.sampleset4.expr1.EFGH/
jogged my memory as to why I though we decided that "samplesetN" was something different than Sudhansu's ongenome dataset accessions (e.g. phavu1). My recollection is that the example above would not have a single dataset accession in ongenome, but we wanted to indicate that the difference here was that a single sampleset was being analyzed in two genomic contexts. 

let me know if you think I'm wrong about that

**Comment by adf-ncgr** [comment]
PS. I'm not sure where the suggested transposition of sampleset to the end originated, but I agree with @cann0010 preferring that expr1 be at the end (and this is what our fait accompli had proposed)

**Comment by cann0010** [comment]
@adf-ncgr - right, it sounds like we disagree in our weak preferences regarding the order. But either is acceptable to me (as long as we pick one). How about we defer to @sdash-github on this one, since he will likely be the primary generator+consumer. Sudhansu: your preference?

**Comment by sammyjava** [comment]
More importantly, the thing before the KEY4 describes the contents:
```
Lee.gnm1.ann1.6NZV
Lee.gnm1.BXNC
mixed.gwas1.1W14
mixed.pheno1.0BYC
Wm82.gnm2.ann1.RVB6
Wm82.gnm2.ann1.samplesetN.expr1.G7ZY
Wm82.gnm2.ann1.syn1.HXNY
Wm82.gnm2.DTC4
Wm82.gnm2.mrk1.XJP2
Zh13.gnm1.ann1.8VV3
Zh13.gnm1.N6C8
```
I thought this was a core principle of the naming: that ann#, gnm#, gwas#, mrk#, syn#, etc. all specify the contents of the directory. Since there are a variety of numbers of terms (gnm1.ann1 vs gnm1, for example), putting it second to last is descriptive, like a file extension.

**Comment by adf-ncgr** [comment]
makes sense to me (and was more or less what I was trying to say)- why'd you have to ruin it by not caring?

**Comment by sdash-github** [comment]
Ref comment above: https://github.com/legumeinfo/datastore/issues/11#issuecomment-624307123  

> following up without the benefit of further side discussion, I think the example (taken from our discussion document):
CDCFrontier.gnm1.ann1.sampleset4.expr1.GHTR/
ICC4958.gnm1.ann1.sampleset4.expr1.EFGH/
jogged my memory as to why I though we decided that "samplesetN" was something different than Sudhansu's ongenome dataset accessions (e.g. phavu1). My recollection is that the example above would not have a single dataset accession in ongenome, but we wanted to indicate that the difference here was that a single sampleset was being analyzed in two genomic contexts.

We also discussed about putting analysis method as another term in case the specific genome-ann-sampmleset gets re-analysed by a more recent method.  But how much granularity of information should we have in the file names? We can include the info about sample sets, analysis methods, etc. as part of metadata of the dataset rather than encode them in the dir name.  This will keep dir names minimal.

**Comment by adf-ncgr** [comment]
My recollection is that at least one of our rationales for including sampleset in the naming is that without the inclusion of sampleset there would be no clear indication that:
CDCFrontier.gnm1.ann1.expr1.GHTR/
CDCFrontier.gnm1.ann1.expr2.HGFD/
refer to different versions of analyses of the same dataset or two different unrelated analyses altogether.

**Comment by sammyjava** [comment]
That's correct, we were thinking that expr1 and expr2 DID refer to two analysis versions of the same underlying data (say HISAT2 versus STAR or HISAT2 v2 versus HISAT2 v3) and the actual RNA-seq experiment should get directory-name exposure.

**Comment by sdash-github** [comment]
I am of the view that this much of details should be in the description rather than in the dir names. Like for example, in the table given at https://legumeinfo.org/lis_expression/all for cicar1 vs. cicar2.

**Comment by cann0010** [comment]
All right. So I think we've converged on ...
GENOGYPE.gnm#.ann#.gensp#.expr#.KEY
... right?

**Comment by sdash-github** [comment]
I can live with it.

**Comment by adf-ncgr** [comment]
If gensp# here serves the same purpose of samplesetN, ie if I see:
CDCFrontier.gnm1.ann1.cicar4.expr1.GHTR/
ICC4958.gnm1.ann1.cicar4.expr1.EFGH/
I will be justified in assuming this is the same dataset analyzed in two contexts;
and if I see
CDCFrontier.gnm1.ann1.cicar4.expr1.GHTR/
CDCFrontier.gnm1.ann1.cicar4.expr2.SHGD/
I will know it is two different versions of analysis of the same dataset in the same context.

Then I guess we've converged. And we will all grit our teeth and cheerfully learn to love file names like:
cicar.CDCFrontier.gnm1.ann1.cicar4.expr1.GHTR.genesSamplesTpm.tsv

When the datastore files have been changed to reflect this convergence, and we have commemorated the solemn finality of this decision in the datastore naming guidance document, we can close this issue.

**Comment by sdash-github** [comment]
CDCFrontier.gnm1.ann1.cicar4.expr1.GHTR/
ICC4958.gnm1.ann1.cicar4.expr1.EFGH/

cicar4 dataset accession can't have two different associated reference genomes. The 'cicar4' in OnGenome schema specifies a combination of ref genome, sample set and analysis method. If the sample set is reused against another ref genome, it will have a different accession, perhaps,  cicar5.  Similarly,  if cicar4 is re-analysed with a different analysis version but the reference genome is the same, it will perhaps be named with accession cicar6.  It is the combination of ref genome, sample set and analysis method that makes a dataset accession; any one of these changes it will have a different accession.

**Comment by adf-ncgr** [comment]
that's precisely why I thought we had previously decided that ongenome dataset accessions were going to go in the metadata files and not the names. 

It sounds like the **lengthy** discussion that we held around that googledoc which was (as I understood it at the time) simply an attempt to harmonize the desires of @sdash-github and @sammyjava with respect to representing expression data in the datastore for consumption by the ongenome loader and intermine loader respectively did not really achieve its intended result.

So should we just drop both sampleset and version from the folder names and call it a day? Thus we would have:
CDCFrontier.gnm1.ann1.expr.GHTR/
ICC4958.gnm1.ann1.expr.EFGH/
which I think is more or less exactly how div is being handled, so I guess that's a win in the consistency/simplicity columns.

I will note that in today's **lengthy** discussion, I was merely trying to reconstruct what I thought we had decided **weeks ago** as reflected in the document and email. Apologies for any frustration with our decision-making process that may be evident in this message, but if there's a better way forward in future when such questions arise I would be very happy to hear suggestions.

**Comment by cann0010** [comment]
"So should we just drop both sampleset and version from the folder names and call it a day? Thus we would have:
CDCFrontier.gnm1.ann1.expr.GHTR/
ICC4958.gnm1.ann1.expr.EFGH/ "

I have to admit: I am much more comfortable with this. 
That's better than trying to cram all the semantics into the directory names. That, in fact, was one of the original rationales for using the keys - which serve as a brief, unique identifier to tie the dataset to the metadata (chiefly the README) ... where we have no constraints on verbosity.

**Comment by adf-ncgr** [comment]
crawling back up the slippery slope of semantic cramming... we could just rely on the key for everything.
this would be similar (I suppose) to things like this:
https://docs.google.com/document/d/1--ttOaD5lJ5fpUglPs_W04ZT_489OeWNowKgwD4_Lig
(referring here to just the URL, not its content or metadata like the title)
when something (e.g. DSCensor) lets users Find and Access datasets by metadata then we'd have no occasion to argue about the remaining banana peels on the semantic slope like 
TT_AhComposite_SujayGowda2012_a.map or our old friend minicore_Dezern.trt
or indeed even jemalong_A17.gnm5.ann1_6

This would I suppose also more or less be the semantic web dream where the CoolURIsDon'tChange but the metadata relating to each resource can change.
Our system right now seems hybrid- how much metadata is enough to provide a browsable structure that gets the person to the README they wanted? 

well, this is certainly a can of worms to open at this point in the evening and I promised myself I'd be opening a can of something else by now. I'm happy to let it stand at 

> "So should we just drop both sampleset and version from the folder names and call it a day? Thus we would have:
CDCFrontier.gnm1.ann1.expr.GHTR/
ICC4958.gnm1.ann1.expr.EFGH/ "
I have to admit: I am much more comfortable with this.

and tilt at these semantically opaque windmills later (with all the unconstrained verbosity of Cervantes crammed into the README.windmill!)

**Comment by cann0010** [comment]
Revisiting this thread in an effort to close it ...

Sudhansu and I talked yesterday and came up with some compromises that I think meet the various objectives with respect to users, curators, and Data Store practices.

I propose the following (which is intended as a RFO):

Expression datasets will be indicated in the directory names with "expr" in the field preceding the key:
  `Genus_species/accession.gnm#.ann#.expr.KEY4`
with this form indicating that the expression data has been analyzed with respect to the gnm#.ann# assembly and annotation.

Expression data that is analyzed with respect to another assembly and annotation would result in a directory name with the same format; the instances are distinguished by the key, and elaborated as needed in the description and other fields in the README:
  `Genus_species/accession.gnm1.ann1.expr.ABCD`
  `Genus_species/accession.gnm2.ann4.expr.ZYXW`

It is conceivable that the Data Store holds an expression resource that has not been analyzed with respect to an assembly and annotation; in that case, the directory name would have the form:
  `Genus_species/accession.expr.KEY4`

Users may learn the contents of these expression collections from the Overview text at the top of the species listings, e.g. https://legumeinfo.org/data/public/Phaseolus_vulgaris/. That text is drawn from the "description" field in the README for each collection. Take the example of the phavu1 data from the Expression page at legumeinfo (https://legumeinfo.org/lis_expression/all). A suitable brief description could be: 
  _An RNA-Seq based gene expression atlas of the common bean cv. Negro jamapa; corresponds with the phavu1 dataset at the legumeinfo expression viewer._
This text could be made more explicit if needed to distinguish multiple mappings of the same dataset (for example).

Rationales for the directory specification above: the philosophy of the Data Store with respect to directory names has been to keep them brief, with regular structure, containing sufficient information to make the data findable - but keeping semantic information minimal. The unique key distinguishes datasets and ties them to their metadata, where the resources can be described in detail and where provenance can be explained. Explicit versioning of assemblies and annotations, and spelling out of their relationships (annotation on an assembly) is something of an exception to the objective of "keeping semantic information minimal" - the exception being justified in this case by the importance and prevalence of assemblies and annotations in the Data Store.

To meet the curator's needs to track the datasets, additional information may be maintained in the directory. Sudhansu and I didn't flesh this out, but it could be an additional file if needed, or information in the README or MANIFESTs. The latter would be my choice if those can be made to work (i.e. preferring not to have new special-purpose files) - but there is precedent for some "additional" files, e.g. the fai indexes and the busco directories. A file like "00_matches_phavu1_resource.txt" could be used if there is a real need that can't be met in another way.

**Comment by adf-ncgr** [comment]
request for clarification: 
there seems to be some ambiguity as to what "accession" refers to in these two cases:
Genus_species/accession.gnm#.ann#.expr.KEY4
Genus_species/accession.expr.KEY4

in the former case, I would imagine it relates to the genome against which the dataset was analyzed. In the latter case, the natural assumption would be that it represents the accession from which the sample is derived. I think we need to nip this ambiguity in the bud (or even the shoot apical meristem). Since this RFO proposes not to put metadata for the samples in the names, I think the logical thing would be to remove accession altogether from the latter example; unless you are thinking of cases in which the data gets assembled then analyzed, in which case I'd assert that it should be handled as:
Genus_species/accession.tcp1.KEY4
with a corresponding
Genus_species/accession.tcp1.expr.KEY4 (not the same KEY4)

**Comment by sdash-github** [comment]
I will add that the curated Excel metadata file can be kept in this dir 
as this is more suitable for compilation and curation of metadata. 
Necessary special format files may be derived from this with a script if 
necessary, e.g., for loading into OnGenome schema and the mines.

**Comment by sammyjava** [comment]
What's "tcp" stand for?

**Comment by adf-ncgr** [comment]
I believe it is being used for "transcriptome" (haven't seen udp yet)

**Comment by sammyjava** [comment]
I think it's always good to visualize what you get, so here's what this edict would result in for our common bean atlas (at least the files that I use):
```
Phaseolus_vulgaris/G19833.gnm1.ann1.expr.4ZDQ/
├── phavu.G19833.gnm1.ann1.expr.4ZDQ.exprSamples.tsv
├── phavu.G19833.gnm1.ann1.expr.4ZDQ.exprSource.tsv
└── phavu.G19833.gnm1.ann1.expr.4ZDQ.genesSamplesTpm.tsv
```
Also: we could shorten those double extensions to samples.tsv, source.tsv and values.tsv if you like. Makes no difference to me but I heard somewhere that shorter file names are desired.

**Comment by sdash-github** [comment]
This is good with examples. I am adding the excel file to the dir.

|Phaseolus_vulgaris/G19833.gnm1.ann1.expr.4ZDQ/ ├── 
phavu.G19833.gnm1.ann1.expr.4ZDQ.exprSamples.tsv ├── 
phavu.G19833.gnm1.ann1.expr.4ZDQ.exprSource.tsv └── 
phavu.G19833.gnm1.ann1.expr.4ZDQ.genesSamplesTpm.tsv |__ ||phavu.G19833.gnm1.ann1.expr.4ZDQ.|metadata.xlsx
||

**Comment by cann0010** [comment]
Regarding the "request for clarification" - honestly, this seems to me like splitting hairs. "In the latter case, the natural assumption would be that it represents the accession from which the sample is derived." Yes: that's what I meant. I don't see the problem. HOWEVER, let's remove this from the spec (Genus_species/accession.expr.KEY4). Let's leave the question of other forms and scenarios for another day. I think I'm not alone in wanting to close this thread. 

Regarding "samples.tsv" preferred over "exprSamples.tsv" - I agree (shorter is better; expr already shows up in the filename).

**Comment by sammyjava** [comment]
I like it. Here's the new dir/files for common bean:
```
Phaseolus_vulgaris/G19833.gnm1.ann1.expr.4ZDQ
├── phavu.G19833.gnm1.ann1.expr.4ZDQ.source.tsv
├── phavu.G19833.gnm1.ann1.expr.4ZDQ.samples.tsv
└── phavu.G19833.gnm1.ann1.expr.4ZDQ.values.tsv
```
I'll rename the DS dirs and files accordingly.

**Comment by adf-ncgr** [comment]
+1 to closing the thread which I thought had been decided several weeks ago and +10 to not bringing in hypotheticals to the spec

**Comment by cann0010** [comment]
Thanks, all. Closing. Will add the expression spec to the "[about the data store](https://github.com/LegumeFederationDataStore/about_the_data_store/blob/master/about_the_Data_Store.md)" document.
