### ISSUE TITLE
RFO: add "synopsis" field to gwas and qtl-exp files

### ISSUE THREAD

**Issue by cann0010** [legumeinfo/datastore#13]
I’d like to propose adding a field, named “synopsis”, to the gwas…gwas.tsv and qtl…expt.tsv files (esp @sammyjava @adf-ncgr)

The Synopsis field would be composed by the curator to be a short (say, <200 character) description of the resource, to be used in generating a descriptive overview of the directory contents, for those browsing at the Data Store. It would be distinct from the Description, which (to this point) has usually been the abstract from the manuscript.

The synopsis would be used to generate a summary header for users to see while browsing in the Data Store - similar to the page header here, for example: https://legumeinfo.org/data/public/Phaseolus_vulgaris/ 

To generate those headers, I use a script (metadata_summarize.sh) to pull out the “subject” field from the README.key4.yml from each collection. (In retrospect, “synopsis” would have been a more descriptive word than “subject.” We also have “description” in the README, and subject-vs-description is confusing.)

For the GWAS and QTL directories, the header would look something like this, in Phaseolus_vulgaris:

```
phavu.mixed.gwas.5HCM.31428109.gwas.tsv.gz
Identifier	31428109
Name	Raggi, Caproni et al., 2019
Description	The aim of this study was to investigate the genetic control of days to flowering using a whole genome association approach on a panel of 

phavu.mixed.gwas.5HCM.31486530.gwas.tsv.gz
Identifier	31486530
Name	Parker, Berny Mier y Teran et al., 2020
Description	GWAS study of pod dehiscence in Phaseolus vulgaris dry beans, using the Andean and Mesoamerican Diversity Panels.
```

(I generated the above examples with this code snippet):
`for file in *gwas.tsv.gz; do echo $file; gzcat $file | awk '$1~/^Iden|^Name/ {print $0} $1~/^Descr/ {print substr($0, 0,150)}'; echo; done
`

**Comment by adf-ncgr** [comment]
No O, but I am not exactly sure I understand what you're proposing here. Can you give an example of what a synopsis would look like vs. the current Description? Or are you saying that those "Descriptions" in the above example would be coming from synopsis fields? I don't have anything against it in principle, as long as curators can understand what's needed enough to do something reasonably coherent; in general, I think Minimal Bar for Subjective (aka non-validatable) Curation is a good standard.

This would probably also be a good time to think about how DSCensor (@ctcncgr) could summarize GWAS/QTL data available. For example, it would be nifty to be able to ask it to list GWAS containing seed-related traits across all species and maybe get some summary of number of genomic loci detected across the experiments (or something like that).

**Comment by cann0010** [comment]
@adf-ncgr  Here's an example of what the two fields might contain for the Parker et al. 2019 manuscript I've been working on (PMID 31486530):

Synopsis: GWAS study of pod dehiscence in Phaseolus vulgaris dry beans, using the Andean and Mesoamerican Diversity Panels.

Description: Pod Dehiscence QTLs were identified using three phenotyping methods and an ICA Bunsi (PD-susceptible) x SXB 405 (PD-resistant) recombinant inbred mapping population.  An unreplicated spring planting of 238 RIL field plots were visually evaluated for dehiscence.  A replicated summer planting produced mature, non-dehiscing pods from 191 RILs that were phenotyped in two ways: the proportion of pods dehiscing after 7 days in a 65 C dessicator and 7 subsequent days at room temperature, and peak force required to induce pod fracture at the apical end of the pod beak measured with an Imada force measurement guage.  Composite interval mapping was completed with the R package R/qtl.

**Comment by adf-ncgr** [comment]
Thanks, that's a good example. I think it is likely somewhat due to the nature of this publication but for me there is some cognitive dissonance between the Synopsis (which references GWAS) and the Description (which references composite interval mapping). I also don't see that in this case the Description was simply lifted from the abstract, or that it is a longer form of the Synopsis- it seems like two curators have made somewhat different decisions on what to abstract into the respective locations. 

In any case, I'm not opposed but I think curators will need some guidance about what salient points ought to be abstracted when possible.

**Comment by sammyjava** [comment]
Fine with me.

**Comment by cann0010** [comment]
OK. I'll plan to retrofit the files with this field, probably starting next week (or so). Closing.
