### ISSUE TITLE
RFO: add MarkerFile field to GWAS and QTL expt files

### ISSUE THREAD

**Issue by cann0010** [legumeinfo/datastore#14]
I propose adding a MarkerFile field to GWAS and QTL/expt files. It is possible that the marker file for such studies doesn't carry the same PMID identifier in the file name - for example, if two GWAS experiments use the same map. Also, an explicit pointer avoids the confusion of (for example) a GWAS file that could conceivably reference a full marker set or just the significant markers, e.g. 
glyma.Wm82.gnm1.mrk.GHRN.LBC201805160-1.gff3.gz
glyma.Wm82.gnm1.mrk.GHRN.soysnp50k.gff3.gz
@sammyjava @adf-ncgr

**Comment by adf-ncgr** [comment]
Thanks, this was just being discussed as an open issue earlier when @ctcncgr was asking about it. I am happy to have a field added, but having it point to a file that is a mapping to one specific genome seems to defeat the purpose. Can we instead say that the referencing would be like:
MarkerSet LBC201805160-1 
and then anything that finds a glyma GWAS with this MarkerSet will be justified in using any of
glyma.Wm82.gnm1.mrk.GHRN.LBC201805160-1.gff3.gz
glyma.Wm82.gnm2.mrk.XYZC.LBC201805160-1.gff3.gz
glyma.Wm82.gnm4.mrk.WTHM.LBC201805160-1.gff3.gz
as the basis of a projection to the relevant genome?

**Comment by sammyjava** [comment]
Agreed, let's keep cross-updates to a minimum in the datastore. If I add a marker mapping to glyma.MyFaveSoy.gnm1, I shouldn't have to keep track of the places those markers may have been used to add a field to their metadata.

**Comment by sammyjava** [comment]
This is, in fact, a general principle: we should put minimal identifying keys in files rather than list the actual files. If there's a case of us doing this, I'd like to know so I can post up a revision.

**Comment by cann0010** [comment]
OK. Will leave the status quo, and will be on the look-out for problematic cases. The current experiment identifier (e.g. "Identifier  LBC201805160-1") may be sufficient, if we use it right 
... Just may require generating some seemingly "extra" (experiment-specific) marker files, as opposed to the full genotype/marker sets.

**Comment by adf-ncgr** [comment]
sorry, just to be clear I would also be happy with (and probably prefer) marker sets that were not experiment specific. I just happened to choose the first file in your examples, but my suggestion would have applied just as well to having in a GWAS experiment file:
MarkerSet soysnp50k

There might be reasons for making experiment-specific subsets of markers, but I don't know what they are and would be a little worried about getting redundancy between experiment-specific files (not that I know that this redundancy would necessarily cause problems...).

**Comment by cann0010** [comment]
@adf-ncgr The general marker sets won't (in general) carry the experiment identifier. So, how to find it?
Also, it seemed that it was being problematic for ZZBrowse to extract the marker subset from the full genotype file?

**Comment by adf-ncgr** [comment]
I thought the idea would be that many experiments might use the same marker set. The marker sets won't carry an experiment identifier, but the mappings for the markers in an experiment can be determined by their reference to the generic set.  I am not sure if the ZZBrowse issue you mention was ultimately resolved but maybe @svengato should comment about that. If there are good reasons for maintaining subset files, I am OK with it.

**Comment by sammyjava** [comment]
> @adf-ncgr The general marker sets won't (in general) carry the experiment identifier. So, how to find it?
> Also, it seemed that it was being problematic for ZZBrowse to extract the marker subset from the full genotype file?

There is a need to associate experiments with marker mappings. That is achieved by a "MarkerSet" addition to the metadata. BUT that is a marker set, hopefully the full set from the chip that was used in the given experiment. We don't need to add experiment-specific marker subsets, but we should tell the user where to find the marker mappings for a given experiment. That's kind of what I've already been doing with the "platform" attributes:
```
PlatformName   Cowpea iSelect Consortium Array
```
but a MarkerSet addition is needed, which in this case would be
```
MarkerSet   Cowpea1MSelectedSNPs
```
and then one can find the marker mappings:
```
IT97K-499-35.gnm1.mrk.52FC/
├── vigun.IT97K-499-35.gnm1.mrk.52FC.Cowpea1MSelectedSNPs.gff3
```
(it's the only file I have for Cowpea, but that's the idea.)

**Comment by sammyjava** [comment]
PS this hasn't been an issue for mine loading because I load ALL the marker GFFs. But I agree that this connection is needed in the experiment files.

**Comment by cann0010** [comment]
Apologies continuing the discussion, but I am now thinking that PlatformName could be sufficient, if we specify how it is to be used - i.e. as a filename identifier indicating a marker set. That's not how the field is currently being used, but this could easily be tweaked. 

Here's what is currently in that field, in Glycine_max/mixed.gwas.1W14/ :
`for file in *gwas.tsv.gz ; do zgrep PlatformName $file; done | sort | uniq -c
   5 PlatformName	
   1 PlatformName	180k Axiom® SoyaSNP array
   1 PlatformName	Golden Gate SNP assay
   1 PlatformName	Illumina GoldenGate assay
   1 PlatformName	IlluminaGoldenGate
   1 PlatformName	NJAU355K Soy SNP assay
   1 PlatformName	NJAU355_KSoySNP
   1 PlatformName	SLAF-seq
   8 PlatformName	SoySNP50K
`

**Comment by adf-ncgr** [comment]
yep, that would be OK by me.

**Comment by sammyjava** [comment]
Yup yup. I've updated the GWAS and QTL file specs accordingly. Let's close this....
